/*
 THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF OUTRAGE
 ENTERTAINMENT, INC. ("OUTRAGE").  OUTRAGE, IN DISTRIBUTING THE CODE TO
 END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
 ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
 IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
 SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
 FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
 CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
 AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.
 COPYRIGHT 1996-2000 OUTRAGE ENTERTAINMENT, INC.  ALL RIGHTS RESERVED.
 */
 //{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NewEditor.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_NUM_MARKED         101
#define ID_MOUSE_POSITION               102
#define ID_INSERT_POSITION              103
#define ID_INDICATOR_GRID_SIZE          104
#define ID_INDICATOR_CURRENT            105
#define ID_INDICATOR_MODE               106
#define IDR_MAINFRAME                   128
#define IDR_D3LTYPE                     129
#define IDI_D3_ICON                     130
#define IDD_LEVELINFO                   131
#define IDD_LOADLEVELPROGRESS           132
#define IDD_CAMERASLEW                  133
#define IDD_SETTINGS                    134
#define IDD_TABLEFILE_MANAGER           137
#define IDD_TABLED_TEXTURES             138
#define IDD_TABLED_OBJECTS              139
#define IDD_TABLED_SOUNDS               140
#define IDD_TABLED_DOORS                141
#define IDD_TEXTUREBAR                  144
#define IDR_TOOLBAR_POPUP               145
#define IDD_TEXTURE_PALETTE             146
#define IDR_ORTHOWND_POPUP              146
#define IDR_LEVELWND_POPUP              147
#define IDD_BAR_LIST                    147
#define IDD_TEXTURE_PROPERTIES          148
#define IDD_ROOMBAR                     149
#define IDR_PERSPWND_POPUP              149
#define IDD_NEWFILE                     150
#define IDR_ORFTYPE                     150
#define IDD_OBJECT_PALETTE              151
#define IDD_OBJECTBAR                   152
#define IDD_OBJECT_PROPERTIES           153
#define IDD_EXTRUDE_FACE                154
#define IDD_LATHE_VERTS                 155
#define IDB_SPLASH                      155
#define IDD_SPLASH                      156
#define IDD_TEXTURE_ALIGN               158
#define IDD_TIPDIALOG                   159
#define IDD_BEND_VERTS                  160
#define IDR_BARLIST_POPUP               160
#define IDD_REF_FRAME                   161
#define IDD_TRIGGERDIALOG               162
#define IDD_EDITLINEDLG                 164
#define IDD_HOGBROWSER                  165
#define IDD_SCRIPTCOMPILE               166
#define IDD_MISSIONHOG                  169
#define IDD_GOALDIALOG                  170
#define IDD_LISTDIALOG                  171
#define IDD_LIGHTINGPROGRESS            172
#define IDD_ROOM_PROPERTIES             173
#define IDD_SAVELISTS                   175
#define IDI_PLAYER_RED                  176
#define IDI_PLAYER_BLUE                 177
#define IDI_PLAYER_GREEN                178
#define IDI_PLAYER_YELLOW               179
#define IDI_PLAYER_INSERT               180
#define IDI_PLAYER_DELETE               181
#define IDI_FACE_TRIANGULATE_CURRENT    205
#define IDI_EDGE_CONTRACT               206
#define IDI_EDGE_EXPAND                 207
#define IDI_FACE_CONTRACT               208
#define IDI_FACE_EXPAND                 209
#define IDI_FACE_FLIP                   210
#define IDI_FACE_JOIN                   211
#define IDI_FACE_PLANAR_CHECK           212
#define IDI_FACE_SPLIT_CURRENT_FACE     213
#define IDI_FACE_TRIANGULATE_NONP       214
#define IDI_MODIFY_BEND                 215
#define IDI_MODIFY_EXTRUDE              216
#define IDI_MODIFY_LATHE                217
#define IDI_MODIFY_SET_REF_FRAME        218
#define IDI_ROOM_CONTRACT               219
#define IDI_ROOM_EXPAND                 220
#define IDI_VERTEX_REMOVE_EXTRAS        221
#define IDI_VERTEX_SNAP_EDGE            222
#define IDI_VERTEX_SNAP_FACE            223
#define IDI_VERTEX_SNAP_GRID            224
#define IDI_VERTEX_SNAP_VERT            225
#define IDD_SOUNDBAR                    227
#define IDD_MATCENS                     228
#define IDD_MATCEN_ATTACH               229
#define IDI_ROTATELEFT                  231
#define IDI_ROTATERIGHT                 232
#define IDI_RIGHT                       233
#define IDI_LEFT                        234
#define IDI_UP                          235
#define IDI_DOWN                        236
#define IDD_MIRROR_ROOM                 237
#define IDI_ROOM_MIRROR                 238
#define IDI_EDGE_ADD_VERT               239
#define IDI_EDGE_REMOVE_VERT            240
#define IDD_PATHBAR                     241
#define IDI_BNODE_CREATE                242
#define IDI_BNODE_DESTROY               243
#define IDI_BNODE_VERIFY                244
#define IDI_BNODE_RESET                 246
#define IDI_ZOOMIN                      249
#define IDI_ORIGINFORWARD               250
#define IDD_DALLAS_MAIN_DIALOG          252
#define IDI_FACE_TWIST                  254
#define IDD_DALLAS_GENERIC_PROMPT_DIALOG 255
#define IDI_FACE_SWAP_VERTS             255
#define IDB_DALLAS_TREE_ICONS_BITMAP    256
#define IDD_TERRAINBAR                  256
#define IDD_DALLAS_VECTOR_DIALOG        258
#define IDD_DALLAS_SOUND_DIALOG         265
#define IDD_DALLAS_FLAG_DIALOG          266
#define IDD_DALLAS_TEXTURE_DIALOG       268
#define IDD_DALLAS_USERTYPES_DIALOG     269
#define IDD_DALLAS_IMPORT_DIALOG        270
#define IDD_DALLAS_STRM_AUDIO_DIALOG    273
#define IDD_DOORWAYBAR                  274
#define IDD_LIGHTINGDIALOG              275
#define IDD_OPENLISTS                   276
#define IDD_MATCEN_PRODUCE              277
#define IDD_MATCEN_DISPLAY              278
#define IDC_EDIT1                       1000
#define IDC_EVENT_TREE                  1000
#define IDC_BUTTON1                     1001
#define IDC_EDIT_B                      1001
#define IDC_EDIT_V                      1001
#define IDC_HELP_EDIT                   1001
#define IDC_PROGRESS1                   1002
#define IDC_ZOOMOUT                     1002
#define IDC_EDIT_C                      1002
#define IDC_CHANGE                      1002
#define IDI_ZOOMOUT                     1002
#define IDC_TITLE_TEXT                  1003
#define IDC_PANRIGHT                    1003
#define IDC_MESSAGE_LIST                1003
#define IDC_SENSSLIDER                  1004
#define IDC_MESSAGE_EDIT                1004
#define IDC_PANLEFT                     1005
#define IDC_PANUP                       1006
#define IDC_NONE_RADIO                  1006
#define IDC_PANDOWN                     1007
#define IDC_SPECIFIC_RADIO              1007
#define IDC_ROTATERIGHT                 1008
#define IDC_ROTATELEFT                  1009
#define IDC_ROTATEUP                    1010
#define IDI_ROTATEUP                    1010
#define IDC_ROTATEDOWN                  1011
#define IDI_ROTATEDOWN                  1011
#define IDC_ORIGINRIGHT                 1012
#define IDC_ORIGINLEFT                  1013
#define IDC_ORIGINUP                    1014
#define IDC_EXPORT_BUTTON               1014
#define IDC_ORIGINDOWN                  1015
#define IDC_ORIGINFORWARD               1016
#define IDC_ORIGINREVERSE               1017
#define IDI_ORIGINREVERSE               1017
#define IDC_ZOOMIN                      1018
#define IDI_VERTEX_SNAP_VERT2           1018
#define IDI_VERTEX_SNAP_GRID2           1019
#define IDC_OPENGL                      1020
#define IDC_INSERT_EVENT_BUTTON         1020
#define IDI_VERTEX_SNAP_FACE2           1020
#define IDC_DIRECT3D                    1021
#define IDI_VERTEX_SNAP_EDGE2           1021
#define IDC_SOFTWARE                    1022
#define IDC_COPY_BUTTON                 1022
#define IDC_SELECTDIR                   1023
#define IDC_DATADIR                     1024
#define IDC_SYSINFOTEXT                 1025
#define IDC_VC_PATH                     1025
#define IDC_VC_BROWSE                   1026
#define IDC_SCRIPT_PATH                 1027
#define IDC_LIST                        1028
#define IDC_SCRIPT_BROWSE               1028
#define IDC_DUMPFILE                    1029
#define IDC_BROWSE_A                    1030
#define IDC_BROWSE_B                    1031
#define IDC_BROWSE_C                    1032
#define IDC_DISPLAY_A                   1033
#define IDC_DISPLAY_B                   1034
#define IDC_DISPLAY_C                   1035
#define IDC_REMOVE_A                    1036
#define IDC_REMOVE_B                    1037
#define IDC_REMOVE_C                    1038
#define IDC_DISPLAY_ALL                 1039
#define IDC_EDIT_A                      1040
#define IDC_BROWSE_HOG_A                1041
#define IDC_BROWSE_HOG_B                1042
#define IDC_BROWSE_HOG_C                1043
#define IDC_HOGFILE_CHOOSE              1043
#define IDC_DOORS                       1043
#define IDC_GOAL_ITEM_ROOM_COMBO        1043
#define IDC_ROOM_DAMAGETYPE             1043
#define IDC_SOUND_COMBO                 1043
#define IDC_D_MINE                      1044
#define IDC_ENDCAPS                     1044
#define IDC_SHOWAGAIN                   1044
#define IDC_DELETE_FACE                 1044
#define IDC_TRIG_ONESHOT                1044
#define IDC_LOCKED                      1044
#define IDC_GOAL_SECONDARY              1044
#define IDC_Z_BUFFER                    1044
#define IDC_REFUELING_CHECK             1044
#define IDC_FACE_CORONA                 1044
#define IDC_CUSTOM_TEX_LIST             1044
#define IDC_PLAYER_RED                  1044
#define IDC_CF_VIEW                     1045
#define IDC_D_OBJECT                    1045
#define IDC_CF_TEXTURENAME              1046
#define IDC_D_TERRAIN                   1046
#define IDC_CF_LIGHT_COLOR              1048
#define IDC_CF_PROPERTIES               1049
#define IDC_CT_VIEW                     1050
#define IDC_CT_TEXTURENAME              1051
#define IDC_NAME                        1052
#define IDC_CT_LIGHT_COLOR              1052
#define IDC_GENERIC_DATA_EDIT           1052
#define IDC_DESIGNER                    1053
#define IDC_NOTES                       1054
#define IDC_CT_PROPERTIES               1054
#define IDC_TEXTURE_GROUP_TAB           1055
#define IDC_TEXTURE_PALETTE             1056
#define IDC_COPYRIGHT                   1057
#define IDC_APPLY_TO_CURRENT            1057
#define IDC_PROPAGATE                   1058
#define IDC_VIEW                        1058
#define IDC_ALIGNMENT                   1059
#define IDC_D_HUD                       1059
#define IDC_APPLY_TO_MARKED             1060
#define IDC_D_WATER                     1060
#define IDC_D_METAL                     1061
#define IDC_GRAB                        1061
#define IDC_D_MARBLE                    1062
#define IDC_D_PLASTIC                   1063
#define IDC_D_FORCEFIELD                1064
#define IDC_D_ANIMATED                  1065
#define IDC_D_DESTROYABLE               1066
#define IDC_D_FLYTHRU                   1067
#define IDC_D_LIGHT                     1068
#define IDC_D_PROCEDURAL                1069
#define IDC_D_LAVA                      1070
#define IDC_D_RUBBLE                    1071
#define IDC_CURSEL                      1074
#define IDC_FACE_JOIN                   1075
#define IDC_FACE_TURN                   1076
#define IDC_FACE_TWIST                  1077
#define IDC_FACE_SWAP_VERTS             1077
#define IDC_LIST1                       1078
#define IDC_FACE_PLANAR_CHECK           1078
#define IDC_OBJECT_GROUP_TAB            1079
#define IDC_FACE_TRIANGULATE_CURRENT    1079
#define IDC_OBJECT_PALETTE              1080
#define IDC_FACE_TRIANGULATE_NONP       1080
#define IDC_CT_OBJECTNAME               1081
#define IDC_FACE_MARK_BAD               1081
#define IDC_CO_OBJECTNAME               1081
#define IDC_FACE_SPLIT_CURRENT_FACE     1081
#define IDC_VERTEX_MERGE                1082
#define IDC_CF_OBJECTNAME               1082
#define IDC_CLO_OBJECTNAME              1082
#define IDC_VERTEX_MAKE_SINGLE          1083
#define IDC_D_POWERUPS                  1084
#define IDC_VERTEX_SNAP_FACE            1084
#define IDC_VERTEX_FORCE_JOIN           1085
#define IDC_D_CLUTTER                   1085
#define IDC_VERTEX_SNAP_EDGE1           1085
#define IDC_D_ROBOTS                    1086
#define IDC_MODIFY_EXTRUDE              1086
#define IDC_D_BUILDINGS                 1087
#define IDC_MODIFY_LATHE                1087
#define IDC_FACE_EXPAND                 1088
#define IDC_MODIFY_BEND                 1089
#define IDC_XAXIS                       1090
#define IDC_FACE_CONTRACT               1090
#define IDC_EDGE_EXPAND                 1091
#define IDC_ZAXIS                       1091
#define IDC_EDGE_CONTRACT               1092
#define IDC_NORMAL                      1092
#define IDC_ROOM_EXPAND                 1093
#define IDC_YAXIS                       1093
#define IDC_ROOM_CONTRACT               1094
#define IDC_DISTANCE                    1094
#define IDC_SIDES                       1095
#define IDC_ANGLE                       1095
#define IDC_MODIFY_SET_REF_FRAME        1095
#define IDC_UV_STRETCHLESS              1095
#define IDC_UV_RIGHT                    1096
#define IDC_FACE_FLIP                   1096
#define IDC_UV_LEFT                     1097
#define IDC_VERTEX_REMOVE_EXTRAS        1097
#define IDC_UV_UP                       1098
#define IDC_VERTEX_SNAP_FACE2           1098
#define IDC_UV_DOWN                     1099
#define IDC_UV_DEFAULT                  1102
#define IDC_UV_STRETCHMORE              1103
#define IDC_UV_ROTRIGHT                 1105
#define IDC_UV_ROTLEFT                  1106
#define IDC_UV_APPLY                    1107
#define IDC_EDIT_U                      1108
#define IDC_TIP_TEXT                    1109
#define IDC_OUTRAGEWEBPAGE              1110
#define IDC_NEXTTIP                     1111
#define IDC_PREVTIP                     1112
#define IDC_CLO_VIEW                    1113
#define IDC_CO_VIEW                     1114
#define IDC_BUTTON2                     1115
#define IDC_UV_EXPAND_V                 1116
#define IDC_PLAYER_NEXT                 1116
#define IDC_VERTEX_SNAP_EDGE            1116
#define IDC_BUTTON4                     1117
#define IDC_VERTEX_SNAP_EDGE2           1117
#define IDC_CO_PROPERTIES               1118
#define IDC_CLO_PROPERTIES              1119
#define IDC_INWARD                      1120
#define IDC_BUTTON5                     1120
#define IDC_OUTWARD                     1121
#define IDC_BUTTON6                     1121
#define IDC_CF_LIGHT_VALUE_RED          1122
#define IDC_CF_LIGHT_VALUE_GREEN        1123
#define IDC_CF_LIGHT_VALUE_BLUE         1124
#define IDC_CT_LIGHT_VALUE_GREEN        1125
#define IDC_CT_LIGHT_VALUE_BLUE         1126
#define IDC_CT_LIGHT_VALUE_RED          1127
#define IDC_HELP_BUTTON                 1128
#define IDC_CT_LIGHT_VALUE_REFLECT      1128
#define IDC_EDIT2                       1129
#define IDC_CF_LIGHT_VALUE_REFLECT      1129
#define IDC_EDIT3                       1130
#define IDC_TRIG_ADDTRIGGER             1132
#define IDC_TRIG_FLOATING               1133
#define IDC_TRIG_EDITNAME               1134
#define IDC_TRIG_EDITSCRIPT             1135
#define IDC_TRIG_DELETE                 1136
#define IDC_TRIG_PLAYER                 1138
#define IDC_TRIG_PLAYERWEAPON           1139
#define IDC_TRIG_ROBOT                  1141
#define IDC_TRIG_ROBOTWEAPON            1142
#define IDC_TRIG_CLUTTER                1143
#define IDC_TRIG_NAME                   1144
#define IDC_TRIG_NUMBER                 1145
#define IDC_TRIG_TYPE                   1146
#define IDC_TRIG_ROOM                   1147
#define IDC_TRIG_PORTAL                 1148
#define IDC_TRIG_FACE                   1149
#define IDC_TRIG_PREVMINE               1150
#define IDC_TRIG_SELECT                 1151
#define IDC_TRIG_NEXTMINE               1152
#define IDC_TRIG_PREVROOM               1153
#define IDC_TRIG_NEXTROOM               1154
#define IDC_FILETYPE                    1156
#define IDC_FILE_LIST                   1157
#define IDC_FILENAME                    1158
#define IDC_VC_DEBUG_OFF                1159
#define IDC_VC_DEBUG_ON                 1160
#define IDC_VC_WARNING_0                1161
#define IDC_VC_WARNING_1                1162
#define IDC_SCRIPTTXT                   1162
#define IDC_VC_WARNING_2                1163
#define IDC_CONFIGURE                   1163
#define IDC_VC_WARNING_3                1164
#define IDC_COMPILE                     1164
#define IDC_VC_WARNING_4                1165
#define IDC_SCRIPTLIST                  1165
#define IDC_OUTPUT                      1166
#define IDC_EDITNAME                    1167
#define IDC_CD_DOORNAME                 1170
#define IDC_PLACE_DOOR                  1171
#define IDC_ATTACH_DOOR                 1172
#define IDC_CDW_DOORNAME                1173
#define IDC_CDW_VIEW                    1174
#define IDC_CD_VIEW                     1175
#define IDC_CDW_PROPERTIES              1176
#define IDC_CD_PROPERTIES               1177
#define IDC_MINE_RADIOSITY              1178
#define IDC_COMBINE_FACES               1179
#define IDC_VOLUME_LIGHTS               1180
#define IDC_SUPER_DETAIL                1181
#define IDC_LIGHTMAP_SPACING            1182
#define IDC_ITERATIONS                  1183
#define IDC_IGNORE_LIMIT                1184
#define IDC_LIGHTS_IN_MINE              1185
#define IDC_UNLOAD                      1186
#define IDC_TERRAIN_RADIOSITY           1186
#define IDC_LIGHTS_ON_TERRAIN           1187
#define IDC_AUTOCLOSE                   1188
#define IDC_GB_IGNORE                   1189
#define IDC_KEY1                        1190
#define IDC_KEY2                        1191
#define IDC_KEY3                        1192
#define IDC_KEY4                        1193
#define IDC_KEY5                        1194
#define IDC_KEY6                        1195
#define IDC_KEY7                        1196
#define IDC_KEY8                        1197
#define IDC_NEEDSALL                    1198
#define IDC_NEEDSONE                    1199
#define IDC_INITIALPOS                  1202
#define IDC_HITPOINTS                   1203
#define IDC_ADD_GOAL                    1204
#define IDC_PREV_GOAL                   1205
#define IDC_NEXT_GOAL                   1206
#define IDC_DELETE_GOAL                 1207
#define IDC_GOAL_SELECT                 1208
#define IDC_GOAL_NUMBER                 1210
#define IDC_GOAL_NAME                   1211
#define IDC_GOAL_LIST_SPIN              1212
#define IDC_GOAL_LIST                   1213
#define IDC_GOAL_PRIORITY               1214
#define IDC_GOAL_ITEM_NUMBER            1215
#define IDC_GOAL_PRIORITY_SPIN          1216
#define IDC_GOAL_DESCRIPTION            1217
#define IDC_GOAL_LOCOBJ_NAME            1218
#define IDC_GOAL_ITEM_ADD               1219
#define IDC_GOAL_ITEM_DELETE            1220
#define IDC_PREV_GOAL_ITEM              1221
#define IDC_NEXT_GOAL_ITEM              1222
#define IDC_GOAL_ITEM_ROOM              1223
#define IDC_GOAL_ITEM_OBJECT            1224
#define IDC_GOAL_ITEM_TRIGGER           1226
#define IDC_GOAL_ITEM_OBJECT_COMBO      1227
#define IDC_ROOM_AMBIENT                1227
#define IDC_GOAL_ITEM_TRIGGER_COMBO     1228
#define IDC_GOAL_ITEM_ACTIVATE          1231
#define IDC_GOAL_ITEM_ENTER             1232
#define IDC_GOAL_ITEM_PICKUP_DESTROY    1233
#define IDC_GOAL_ITEM_PLAYER_COLLIDE    1234
#define IDC_GOAL_ITEM_PLAYER_WEAPON     1235
#define IDC_GOAL_ITEM_SELECT            1236
#define IDC_GOAL_ITEM_DALLAS            1237
#define IDC_GOAL_ENABLED                1238
#define IDC_GOAL_COMPLETED              1239
#define IDC_GOAL_GB_KNOWS               1240
#define IDC_GOAL_LOC_BASED              1241
#define IDC_GOAL_OBJECTIVE              1242
#define IDC_GOAL_SUMMARY                1243
#define IDC_HEADER_TEXT                 1245
#define IDC_STATUS_TEXT                 1246
#define IDC_ITERATION_TEXT              1247
#define IDC_STOPLIGHTING                1248
#define IDC_PORTAL_DEPTH                1249
#define IDC_PORTAL_DEPTH_SPIN           1250
#define IDC_ALL_ROOMS                   1251
#define IDC_DISPLAY_BY_DEPTH            1252
#define IDC_REDGOAL_CHECK               1253
#define IDC_BLUEGOAL_CHECK              1254
#define IDC_GREENGOAL_CHECK             1255
#define IDC_YELLOWGOAL_CHECK            1256
#define IDC_SPECIAL1_CHECK              1257
#define IDC_SPECIAL2_CHECK              1258
#define IDC_SPECIAL3_CHECK              1259
#define IDC_SPECIAL4_CHECK              1260
#define IDC_SPECIAL5_CHECK              1261
#define IDC_SPECIAL6_CHECK              1262
#define IDC_SECRET_CHECK                1264
#define IDC_ROOM_NAME                   1266
#define IDC_CURRENTFACE                 1268
#define IDC_MARKEDFACES                 1269
#define IDC_DEFAULTSETTINGS             1270
#define IDC_NEXT_DOORWAY                1271
#define IDC_PREV_DOORWAY                1272
#define IDC_DELETE_DOORWAY              1273
#define IDC_ROOM_DAMAGEAMOUNT           1274
#define IDC_RADIO_NO_MIRROR             1276
#define IDC_RADIO_MIRROR_FACE           1277
#define IDC_SET_MIRROR                  1278
#define IDC_FACE_GOAL_CHECK             1279
#define IDC_FOG_ENABLE                  1280
#define IDC_FOG_DEPTH                   1281
#define IDC_MIRROR_FACE                 1282
#define IDC_FOG_RED                     1283
#define IDC_FOG_GREEN                   1284
#define IDC_FOG_BLUE                    1285
#define IDC_CLEAR_LIGHTMAPS             1286
#define IDC_WIND_X                      1286
#define IDC_ROOM_RADIOSITY              1287
#define IDC_WIND_Y                      1287
#define IDC_ROOM_AMBIENCE_RED           1288
#define IDC_WIND_Z                      1288
#define IDC_ROOM_AMBIENCE_GREEN         1289
#define IDC_ROOM_AMBIENCE_BLUE          1290
#define IDC_ROOM_MULTIPLIER             1291
#define IDC_AMBIENCE_RED                1292
#define IDC_FACE_MULTIPLIER             1293
#define IDC_ROOM_CLEAR_LIGHTMAPS        1294
#define IDC_ROOM_COUNT_LIGHTS           1295
#define IDC_ROOM_FILL_CORONAS           1296
#define IDC_AMBIENCE_GREEN              1297
#define IDC_AMBIENCE_BLUE               1298
#define IDC_MULTIPLIER                  1299
#define IDC_FILL_CORONAS                1300
#define IDC_ROOM_RESET_MULTIPLES        1301
#define IDC_RESET_MULTIPLES             1302
#define IDC_SHELL_FACES                 1303
#define IDC_NON_SHELL_FACES             1304
#define IDC_PORTAL_FACES                1305
#define IDC_FLOATING_TRIGGERS           1308
#define IDC_DISPLAY_ONE_ROOM            1309
#define IDC_RADIO1                      1310
#define IDC_RADIO2                      1311
#define IDC_RADIO3                      1312
#define IDC_LEVEL_TEX_LIST              1313
#define IDC_CUSTOM_OBJ_LIST             1314
#define IDC_LEVEL_OBJ_LIST              1315
#define IDC_UV_FLIP_X                   1316
#define IDC_UV_FLIP_Y                   1317
#define IDC_UV_SHRINK_V                 1318
#define IDC_UV_ROTATE_90                1319
#define IDC_UV_EDIT_STEP                1320
#define IDC_UV_ALIGN_MARKED             1321
#define IDC_UV_EXPAND_U                 1322
#define IDC_UV_SHRINK_U                 1323
#define IDC_UV_FACE_MAP                 1324
#define IDC_UV_ALIGN_EDGE               1326
#define IDC_PLAYER_PREV                 1327
#define IDC_PLAYER_BLUE                 1328
#define IDC_PLAYER_GREEN                1329
#define IDC_PLAYER_YELLOW               1330
#define IDC_PLAYER_DELETE               1331
#define IDC_SOUND_INSERT                1333
#define IDC_SOUND_DELETE                1337
#define IDC_WIND_MAKE                   1339
#define IDC_WIND_SPEED                  1340
#define IDC_VERTEX_SNAP_VERT            1343
#define IDC_VERTEX_SNAP_GRID            1344
#define IDC_SOUND_BROWSE                1345
#define IDC_SOUND_PLAY                  1345
#define IDC_VERTEX_SNAP_VERT2           1345
#define IDC_SOUND_NAME                  1346
#define IDC_VERTEX_SNAP_GRID2           1346
#define IDC_SOUND_VOLUME                1347
#define IDC_MATCEN_NEW                  1348
#define IDC_MATCEN_PREV                 1349
#define IDC_MATCEN_NEXT                 1350
#define IDC_MATCEN_DELETE               1351
#define IDC_MATCEN_NAME                 1352
#define IDC_MATCEN_NUMBER               1353
#define IDC_MATCEN_ROOM_OBJECT_COMBO    1354
#define IDC_MISC_ALLOWOBJECTSTHROUGHWALLS 1355
#define IDC_MATCEN_OBJECT_ATTACH        1356
#define IDC_MATCEN_UNASSIGNED_ATTACH    1357
#define IDC_MATCEN_ROOM_ATTACH          1358
#define IDC_MATCEN_SPAWN_0              1359
#define IDC_MATCEN_SPAWN_2              1360
#define IDC_MATCEN_SPAWN_1              1361
#define IDC_MATCEN_SPAWN_3              1362
#define IDC_MATCEN_SPAWN_NUM            1363
#define IDC_MATCEN_OBJTYPE_NUM          1364
#define IDC_MATCEN_PROD_0_LIST          1365
#define IDC_MATCEN_PROD_0_QUANTITY      1366
#define IDC_MATCEN_PROD_0_SECONDS       1367
#define IDC_MATCEN_PROD_0_PRIORITY      1368
#define IDC_MATCEN_PROD_1_LIST          1369
#define IDC_MATCEN_PROD_1_QUANTITY      1370
#define IDC_MATCEN_PROD_1_SECONDS       1371
#define IDC_MATCEN_PROD_1_PRIORITY      1372
#define IDC_MATCEN_PROD_2_LIST          1373
#define IDC_MATCEN_PROD_2_QUANTITY      1374
#define IDC_MATCEN_PROD_2_SECONDS       1375
#define IDC_MATCEN_PROD_2_PRIORITY      1376
#define IDC_MATCEN_PROD_3_LIST          1377
#define IDC_MATCEN_PROD_3_QUANTITY      1378
#define IDC_MATCEN_PROD_3_SECONDS       1379
#define IDC_MATCEN_PROD_3_PRIORITY      1380
#define IDC_MATCEN_PROD_4_LIST          1381
#define IDC_MATCEN_PROD_4_QUANTITY      1382
#define IDC_MATCEN_PROD_4_SECONDS       1383
#define IDC_MATCEN_PROD_4_PRIORITY      1384
#define IDC_MATCEN_PROD_5_LIST          1385
#define IDC_MATCEN_PROD_5_QUANTITY      1386
#define IDC_MATCEN_PROD_5_SECONDS       1387
#define IDC_MATCEN_PROD_5_PRIORITY      1388
#define IDC_MATCEN_PROD_6_LIST          1389
#define IDC_MATCEN_PROD_6_QUANTITY      1390
#define IDC_MATCEN_PROD_6_SECONDS       1391
#define IDC_MATCEN_PROD_6_PRIORITY      1392
#define IDC_MATCEN_PROD_7_LIST          1393
#define IDC_MATCEN_PROD_7_QUANTITY      1394
#define IDC_MATCEN_PROD_7_SECONDS       1395
#define IDC_MATCEN_PROD_7_PRIORITY      1396
#define IDC_MATCEN_WPN_RADIO            1397
#define IDC_MATCEN_APV_RADIO            1398
#define IDC_MATCEN_SC_RADIO             1399
#define IDC_MATCEN_APN_RADIO            1400
#define IDC_MATCEN_WPV_RADIO            1401
#define IDC_MATCEN_TAB                  1402
#define IDC_PLAYER_NUMBER               1405
#define IDC_MATCEN_PRODUCE_RANDOM       1406
#define IDC_MATCEN_PRODUCE_ORDERED      1407
#define IDC_MATCEN_PRODUCE_ENABLED      1408
#define IDC_MATCEN_PRODUCE_HURT         1409
#define IDC_MATCEN_PRODUCE_MAX          1410
#define IDC_MATCEN_PRODUCE_MULT         1411
#define IDC_MATCEN_PRODUCE_MAXALIVE     1412
#define IDC_MATCEN_PRODUCE_PRETIME      1413
#define IDC_MATCEN_PRODUCE_POSTTIME     1414
#define IDC_DISPLAY_ACTIVE_SOUND        1415
#define IDC_DISPLAY_PROD_SOUND          1416
#define IDC_DISPLAY_PROD_EFFECT         1417
#define IDC_DISPLAY_PROD_TEXTURE        1418
#define IDC_FACE_ADD_VERT               1419
#define IDC_FACE_REMOVE_VERT            1420
#define IDC_ROOM_MIRROR                 1421
#define IDC_BNODE_RADIO                 1422
#define IDC_BNODE_CREATE                1423
#define IDC_BNODE_VERIFY                1424
#define IDC_BNODE_DESTROY               1425
#define IDC_PATH_RADIO                  1427
#define IDC_BNODE_AUTO_MAKE_EDGES       1428
#define IDC_BNODE_AUTO_EDGE_ROOM        1429
#define IDC_UNPLACE_DOOR                1431
#define IDC_EDITTYPE                    1432
#define IDC_EDITID                      1433
#define IDC_EDITFRAMES                  1434
#define IDC_EDITFILENAME                1435
#define IDC_EDIT_RED                    1436
#define IDC_EDIT_GREEN                  1437
#define IDC_EDIT_BLUE                   1438
#define IDC_EDIT_ALPHA                  1439
#define IDC_EDIT_REFLECTIVITY           1440
#define IDC_EDIT_SLIDE_U                1441
#define IDC_EDIT_SLIDE_V                1442
#define IDC_EDIT_SPEED                  1443
#define IDC_VERTEX_CURRENT              1444
#define IDC_WAYPOINT_INSERT             1445
#define IDC_WAYPOINT_DELETE             1446
#define IDC_FACE_TWIST2                 1447
#define IDC_TERRAIN_OCCLUSION           1448
#define IDC_IMPORT_PCX_MAP              1449
#define IDC_EXPORT_PCX_MAP              1450
#define IDC_SKY_EXPAND                  1451
#define IDC_SKY_CONTRACT                1452
#define IDC_SKY_DAMAGE                  1453
#define IDC_SKY_STARS                   1454
#define IDC_SKY_SATELLITES              1455
#define IDC_EDIT                        1456
#define IDC_SKY_NEXT_SAT                1456
#define IDC_SKY_PREV_SAT                1457
#define IDC_SKY_FOG                     1458
#define IDC_ROOM_EXTERNAL               1459
#define IDC_TOUCHES_TERRAIN             1460
#define IDC_SKY_ROTATE_SKY              1461
#define IDC_SKY_ROTATE_STARS            1462
#define IDC_SKY_TEXTURED                1463
#define IDC_SKY_FOG_SCALAR              1465
#define IDC_SKY_ROT_DEG                 1466
#define IDC_SKY_MOVE_SAT_CLOSER         1467
#define IDC_SKY_MOVE_SAT_FARTHER        1468
#define IDC_SKY_MORE_SATS               1469
#define IDC_SKY_LESS_SATS               1470
#define IDC_SKY_NUM_SAT                 1471
#define IDC_SKY_QUANT_SAT               1472
#define IDC_SKY_HALO                    1473
#define IDC_SKY_ATMOSPHERE              1474
#define IDC_SKY_SAT_MOVE_DOWN           1475
#define IDC_SKY_SAT_MOVE_UP             1476
#define IDC_SKY_SAT_MOVE_LEFT           1477
#define IDC_DYNAMIC_TERRAIN_LIGHT       1477
#define IDC_SKY_SAT_MOVE_RIGHT          1478
#define IDC_TOGGLE_CELL_VISIBLE         1479
#define IDC_TERRAIN_SELECT              1480
#define IDC_FORCE_CELL_VISIBLE          1482
#define IDC_INSERT_MINE                 1483
#define IDC_INSERT_TERRAIN              1484
#define IDC_TERRAIN_LOD                 1485
#define IDC_PROMPT                      1769
#define IDC_NEW_EVENT_BUTTON            2307
#define IDC_PASTE_BUTTON                2308
#define IDC_DELETE_EVENT_BUTTON         2309
#define IDC_IMPORT_BUTTON               2310
#define IDC_NEW_MESSAGE_BUTTON          2311
#define IDC_DELETE_MESSAGE_BUTTON       2312
#define IDC_EXPAND_ALL_BUTTON           2313
#define IDC_COLLAPSE_ALL_BUTTON         2314
#define IDC_GENERIC_PROMPT_STATIC       2322
#define IDC_CHANGE_MESSAGE_NAME_BUTTON  2323
#define IDC_DATA1_EDIT                  2326
#define IDC_DATA3_EDIT                  2327
#define IDC_DATA2_EDIT                  2328
#define IDC_SAVE_BUTTON                 2335
#define IDC_HIGHLIGHT_BUTTON            2355
#define IDC_UTYPES_BUTTON               2357
#define IDC_PLAY_SOUND_BUTTON           2376
#define IDC_STOP_SOUNDS_BUTTON          2377
#define IDC_SOUND_LIST                  2378
#define IDC_FLAG_LIST                   2380
#define IDC_FLAG_PROMPT_STATIC          2381
#define IDC_TEXTURE_LIST                2382
#define IDC_UTYPE_COMBO                 2387
#define IDC_VALUES_LIST                 2388
#define IDC_CHANGE_BUTTON               2389
#define IDC_ADD_BUTTON                  2390
#define IDC_DELETE_BUTTON               2391
#define IDC_ALLOBJ_RADIO                2397
#define IDC_ALLTRIG_RADIO               2398
#define IDC_LEVEL_RADIO                 2399
#define IDC_SCRIPT_LIST                 2403
#define IDC_STRM_AUDIO_LIST             2415
#define IDC_PLAY_STRM_AUDIO_BUTTON      2416
#define IDC_EVENT_RADIO                 2455
#define IDC_EVENT_COMBO                 2456
#define ID_FILE_OPENLEVEL               32771
#define ID_FILE_SHOWLEVELSTATS          32772
#define ID_FILE_EDITLEVELINFO           32773
#define ID_FILE_SETTINGS                32775
#define ID_FILE_SAVEAS                  32777
#define ID_TABLEFILE_MANAGER            32784
#define ID_VIEW_TEXTURES                32785
#define ID_VIEW_CAMERASLEWER            32787
#define ID_VIEW_ROOMBAR                 32788
#define ID_SHOW_ATCH_ROOMS              32790
#define ID_SHOW_VERTS                   32791
#define ID_SHOW_NORMALS                 32792
#define ID_SHOW_GRID                    32793
#define ID_GRID_SIZE_1                  32794
#define ID_GRID_SIZE_2                  32795
#define ID_GRID_SIZE_3                  32796
#define ID_GRID_SIZE_4                  32797
#define ID_GRID_SIZE_5                  32798
#define ID_TEXTURED                     32800
#define ID_WIREFRAME                    32801
#define ID_CENTER_ROOM                  32802
#define ID_CENTER_MINE                  32803
#define ID_UNMARK_ALL                   32805
#define ID_MARK_ALL                     32806
#define ID_INVERT_MARKINGS              32807
#define ID_MARK_TOGGLE                  32808
#define ID_VIEW_OBJECTS                 32809
#define ID_CENTER_ORIGIN                32811
#define ID_EDIT_COPY_VERTS              32816
#define ID_EDIT_INSERT_VERT             32817
#define ID_EDIT_DELETE_VERTEX           32818
#define ID_EDIT_INSERT                  32819
#define ID_EDIT_COPY_FACES              32822
#define ID_EDIT_CUT_FACES               32824
#define ID_EDIT_CUT_VERTS               32825
#define ID_DISPLAY_CURRENTROOMVIEW      32826
#define ID_HELP_CHECKFORUPDATES         32827
#define ID_HELP_SHOWTIPS                32833
#define ID_FILE_SHOWROOMSTATS           32835
#define ID_ZBUFFER                      32843
#define ID_ADDTOCUSTOM                  32844
#define ID_REMOVE                       32845
#define ID_VIEW_MOVECAMERATOCURRENTFACE 32846
#define ID_WINDOW_TEXTUREALIGNMENT      32847
#define ID_WINDOW_TRIGGERS              32848
#define ID_SNAP_TO_GRID                 32849
#define ID_SCRIPTCOMPILE                32850
#define ID_CENTER_FACE                  32851
#define ID_FILE_DALLASVISUALSCRIPTINTERFACE 32852
#define ID_VIEW_DOORWAYS                32853
#define ID_VIEW_LIGHTING                32855
#define ID_BUTTON_BOA_VIS               32856
#define ID_DATA_MISSIONHOGSETTINGS      32857
#define ID_WINDOW_GOALS                 32858
#define ID_FILE_SAVE_ROOM               32859
#define ID_FILE_SAVEASROOM              32860
#define ID_FILE_VERIFY_MINE             32861
#define ID_FILE_VERIFY_ROOM             32863
#define ID_FILE_MN3PACKAGER             32864
#define ID_SHOW_OBJECTS                 32865
#define ID_HELP_CONTENTS                32866
#define ID_FILE_ROOM_PROPERTIES         32868
#define ID_WINDOW_ROOMPROPERTIES        32869
#define ID_FILE_REMOVEEXTRAPOINTS_ROOM  32870
#define ID_MODE_VERTEX                  32871
#define ID_MODE_FACE                    32872
#define ID_MODE_OBJECT                  32873
#define ID_EDIT_DELETE                  32874
#define ID_GRID_SIZE_0                  32875
#define ID_EDIT_ADDSELECT               32875
#define ID_EDIT_REMOVESELECT            32876
#define ID_EDIT_SELECTATTACHED          32877
#define ID_EDIT_LOADSCRAP               32878
#define ID_EDIT_SAVESCRAP               32879
#define ID_EDIT_CLEARSELECTED           32880
#define ID_DEFAULT_EXTRUDE              32886
#define ID_GRID_SIZE_6                  32887
#define ID_GRID_SIZE_CUSTOM             32890
#define ID_VIEW_TEXTURED_OUTLINE        32891
#define ID_SAVELIST                     32892
#define ID_LOADLIST                     32893
#define ID_FILE_SAVERESOURCELISTS       32894
#define ID_FILE_OPENRESOURCELISTS       32895
#define ID_FILE_GRAVITY                 32896
#define ID_MOVELEVEL                    32897
#define ID_MOVE_MINE                    32898
#define ID_VIEW_SOUNDS                  32899
#define ID_SHOWROOMCENTER               32902
#define ID_WINDOW_MATCENS               32903
#define ID_FILE_SCALEMINE               32904
#define ID_REMOVE_ALL                   32905
#define ID_MODE_PATH                    32906
#define ID_WINDOW_PATHBAR               32907
#define ID_EDIT_UNPLACEGROUP            32910
#define ID_SOUNDS                       32911
#define ID_EDIT_PASTEONTOP              32912
#define ID_VIEW_MOVECAMERATOCURRENTROOM 32913
#define ID_ROOM_ADD                     32918
#define ID_ROOM_SELECTBYNUMBER          32919
#define ID_WINDOW_EDITORBAR             32919
#define ID_WINDOW_EDITORBAR2            32920
#define ID_WINDOW_TERRAINBAR            32922
#define ID_ROOM_GRABTEXTURE             32927
#define ID_ROOM_ATTACHROOM              32940
#define ID_ROOM_BUILDBRIDGE             32945
#define ID_ROOM_MARK                    32946
#define ID_ROOM_PLACEROOM               32954
#define ID_ROOM_UNPLACEROOM             32955
#define ID_ROOM_DELETE                  32956
#define ID_EDIT_ATTACH                  32958
#define ID_ROOM_SELECTFACEBYNUMBER      32960
#define ID_ROOM_DROPROOM                32964
#define ID_ROOM_PLACETERRAINROOM        32965
#define ID_ROOM_JOINROOMS               32966
#define ID_ROOM_SWAPMAKEDANDCURRENTROOMFACE 32967
#define ID_ROOM_DELETEFACE              32976
#define ID_ROOM_SNAPPLACEDROOM          32977
#define ID_ROOM_JOIN_ADJACENT_FACES     32983
#define ID_ROOM_PROPAGATETOALL          32985
#define ID_ROOM_SPLITFACE               32986
#define ID_ROOM_DELETEPORTAL            32987
#define ID_ROOM_SNAPPOINTTOEDGE         32996
#define ID_ROOM_SNAPPOINTTOPOINT        32998
#define ID_FILE_REMOVEEXTRAPOINTS       33000
#define ID_ROOM_BUILDSMOOTHBRIDGE       33002
#define ID_ROOM_JOINROOMSEXACT          33004
#define ID_VIEW_MOVECAMERATOCURRENTOBJECT 33021
#define ID_ROOM_COMBINE                 33029
#define ID_ROOM_SNAPPOINTTOFACE         33031
#define ID_ROOM_LINKTONEWEXTERNAL       33033
#define ID_ROOM_DELETEVERT              33037
#define ID_VIEW_MOVECAMERATOSELECTEDFACE 33042
#define ID_VIEW_MOVECAMERATOSELECTEDROOM 33043
#define ID_ROOM_MERGEOBJECTINTOROOM     33044
#define ID_EDIT_PLACE_TERRAIN           33045
#define ID_POSITION                     59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        257
#define _APS_NEXT_COMMAND_VALUE         32924
#define _APS_NEXT_CONTROL_VALUE         1486
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
