/*
 THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF OUTRAGE
 ENTERTAINMENT, INC. ("OUTRAGE").  OUTRAGE, IN DISTRIBUTING THE CODE TO
 END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
 ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
 IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
 SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
 FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
 CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
 AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.
 COPYRIGHT 1996-2000 OUTRAGE ENTERTAINMENT, INC.  ALL RIGHTS RESERVED.
 */
 


#ifndef __SCRIPTCOMPILERAPI_H_
#define __SCRIPTCOMPILERAPI_H_

#include "pstypes.h"

#define ST_LEVEL	0
#define ST_GAME		1
typedef struct{
	char source_filename[_MAX_PATH];
	ubyte script_type;
	void (*callback)(char *str);
}tCompilerInfo;

#define CERR_NOERR				0
#define CERR_NOCOMPILERDEFINED	1
#define CERR_COMPILERMISSING	2
#define CERR_SOURCENOEXIST		3


int ScriptCompile(tCompilerInfo *ci);
bool ScriptCreateEmptyScript(char *filename,ubyte script_type);
#endif